# Generated by Django 4.2.7 on 2026-06-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.IntegerField(db_index=True)),
                ('agent_name', models.CharField(max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('intent', models.CharField(blank=True, max_length=50)),
                ('model_used', models.CharField(max_length=100)),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('tokens_total', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token Usage Log',
                'verbose_name_plural': 'Token Usage Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_id', 'date'], name='budget_toke_agent_i_628ed2_idx')],
            },
        ),
    ]
