# Generated by Django 4.2.7 on 2026-06-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='FileMaster',
        ),
        migrations.DeleteModel(
            name='Head',
        ),
        migrations.RemoveField(
            model_name='historicalblog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalblog',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalblogcategory',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalblogcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='historicalblogimage',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='historicalblogimage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfilemaster',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalhead',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalimagemaster',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsitesetting',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='ImageMaster',
        ),
        migrations.DeleteModel(
            name='SiteSetting',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
        migrations.DeleteModel(
            name='HistoricalBlog',
        ),
        migrations.DeleteModel(
            name='HistoricalBlogCategory',
        ),
        migrations.DeleteModel(
            name='HistoricalBlogImage',
        ),
        migrations.DeleteModel(
            name='HistoricalContact',
        ),
        migrations.DeleteModel(
            name='HistoricalFileMaster',
        ),
        migrations.DeleteModel(
            name='HistoricalHead',
        ),
        migrations.DeleteModel(
            name='HistoricalImageMaster',
        ),
        migrations.DeleteModel(
            name='HistoricalSiteSetting',
        ),
    ]
