# Generated by Django 4.2.7 on 2026-06-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('whatsapp_name', models.CharField(blank=True, help_text='pushname from wweb-mcp. Auto-populated.', max_length=100)),
                ('real_name', models.CharField(blank=True, help_text='Manually confirmed real name.', max_length=100)),
                ('role', models.CharField(blank=True, help_text='e.g. Sales Rep, CEO, Community Member.', max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('trust_level', models.CharField(choices=[('unknown', 'Unknown — new contact'), ('member', 'Regular member'), ('trusted', 'Trusted — manually elevated'), ('team', 'WOLFx team member'), ('blocked', 'Blocked — ignore all messages')], default='unknown', max_length=20)),
                ('groups', models.JSONField(default=list, help_text='List of channel_ids this person is active in.')),
                ('preferences', models.JSONField(default=dict, help_text='Communication style and preferences learned over time.')),
                ('embedding', models.JSONField(default=list, help_text='pgvector embedding of this person profile.')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Person Entity',
                'verbose_name_plural': 'Person Entities',
                'ordering': ['-last_active'],
                'indexes': [models.Index(fields=['phone_number'], name='memory_pers_phone_n_6089e2_idx'), models.Index(fields=['trust_level'], name='memory_pers_trust_l_cbb8f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='EpisodicMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100)),
                ('sender', models.CharField(blank=True, help_text='Phone number if user-scoped, empty if group-scoped.', max_length=100)),
                ('scope', models.CharField(choices=[('group', 'Group'), ('user', 'User')], default='group', max_length=20)),
                ('summary', models.TextField(help_text='LLM-generated summary of the session.')),
                ('key_entities', models.JSONField(default=list, help_text='Company names, person names mentioned.')),
                ('key_decisions', models.JSONField(default=list, help_text='Decisions or action items from the session.')),
                ('session_start', models.DateTimeField()),
                ('session_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Episodic Memory',
                'verbose_name_plural': 'Episodic Memories',
                'ordering': ['-session_end'],
                'indexes': [models.Index(fields=['channel_id', 'scope'], name='memory_epis_channel_3c1f41_idx'), models.Index(fields=['sender'], name='memory_epis_sender_de8471_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntityMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('company', 'Company'), ('industry', 'Industry'), ('topic', 'Topic'), ('insight', 'Strategic Insight')], max_length=20)),
                ('entity_name', models.CharField(db_index=True, max_length=200)),
                ('scope', models.CharField(choices=[('global', 'Global — accessible to all agents'), ('group', 'Group — accessible within specific channel only')], default='global', max_length=20)),
                ('scope_id', models.CharField(blank=True, help_text='channel_id if group-scoped.', max_length=100)),
                ('known_facts', models.JSONField(default=dict, help_text='Structured facts: founded, size, HQ, product, etc.')),
                ('raw_notes', models.TextField(blank=True, help_text='Unstructured research notes.')),
                ('embedding', models.JSONField(default=list, help_text='pgvector embedding — 1536 dimensions. Replace with VectorField when pgvector installed.')),
                ('confidence', models.FloatField(default=1.0, help_text='How fresh and reliable this data is. Decays over time.')),
                ('source', models.CharField(blank=True, help_text='web, linkedin, apollo, crm, manual.', max_length=50)),
                ('last_researched', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entity Memory',
                'verbose_name_plural': 'Entity Memories',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_name'], name='memory_enti_entity__7511c9_idx'), models.Index(fields=['scope', 'scope_id'], name='memory_enti_scope_3cf210_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text='WhatsApp group ID or Slack channel ID.', max_length=100)),
                ('sender', models.CharField(blank=True, help_text='Sender phone number.', max_length=100)),
                ('sender_name', models.CharField(blank=True, help_text='Resolved display name.', max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('message', models.TextField()),
                ('intent', models.CharField(blank=True, help_text='Classified intent of this message.', max_length=50)),
                ('tool_calls', models.JSONField(default=list, help_text='Tools called during this turn.')),
                ('tokens_used', models.IntegerField(default=0)),
                ('sql_used', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conversation Log',
                'verbose_name_plural': 'Conversation Logs',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['channel_id', 'created_at'], name='memory_conv_channel_0c1c23_idx'), models.Index(fields=['sender', 'created_at'], name='memory_conv_sender_1ef660_idx')],
            },
        ),
    ]
