# Generated by Django 4.2.7 on 2026-06-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agent_type', models.CharField(help_text='Maps to a Python class in agents/registry.py', max_length=50)),
                ('system_prompt', models.TextField(help_text='Agent-specific capabilities and knowledge.')),
                ('personality_prompt', models.TextField(help_text='Tone, relationship style, and communication rules.')),
                ('enabled_tools', models.JSONField(default=list, help_text='List of tool names this agent can use.')),
                ('memory_layers', models.JSONField(default=list, help_text='Which memory layers to retrieve: conversation, episodic, semantic, entity.')),
                ('sender_name_map', models.JSONField(default=dict, help_text='Phone number → display name map. Auto-populated via pushname.')),
                ('authorised_numbers', models.TextField(blank=True, help_text='Comma-separated authorised sender numbers. Empty = allow all.')),
                ('context_window', models.PositiveIntegerField(default=10)),
                ('memory_staleness_days', models.IntegerField(default=7, help_text='Days before cached research is considered stale.')),
                ('daily_token_limit', models.IntegerField(default=50000)),
                ('monthly_token_limit', models.IntegerField(default=500000)),
                ('max_tokens_per_call', models.IntegerField(default=2000)),
                ('max_iterations', models.IntegerField(default=5, help_text='Max LangGraph ReAct iterations per request.')),
                ('alert_at_pct', models.IntegerField(default=80, help_text='Alert when this % of daily token budget is consumed.')),
                ('tool_model_map', models.JSONField(default=dict, help_text='Tool name → model name override. e.g. {"crm_query": "gpt-5-nano"}')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Config',
                'verbose_name_plural': 'Agent Configs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('slack', 'Slack')], max_length=20)),
                ('channel_id', models.CharField(help_text='WhatsApp group ID or Slack channel ID.', max_length=100)),
                ('bot_number', models.CharField(help_text='Bot number used to detect @mentions.', max_length=50)),
                ('api_base', models.CharField(help_text='MCP server base URL for this channel.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_bindings', to='config.agentconfig')),
            ],
            options={
                'verbose_name': 'Channel Binding',
                'verbose_name_plural': 'Channel Bindings',
                'unique_together': {('channel_type', 'channel_id')},
            },
        ),
        migrations.CreateModel(
            name='GlobalPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('content', models.TextField(help_text='Non-negotiable instructions applied to all agents.')),
                ('is_active', models.BooleanField(default=False, help_text='Only one GlobalPrompt should be active at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Prompt',
                'verbose_name_plural': 'Global Prompts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('time', 'One-time Time-based'), ('schedule', 'Recurring Cron Schedule'), ('signal', 'Signal-based')], max_length=20)),
                ('trigger_at', models.DateTimeField(blank=True, help_text='For time-based triggers.', null=True)),
                ('cron_expression', models.CharField(blank=True, help_text='For recurring schedule triggers. e.g. 0 9 * * 1', max_length=100)),
                ('signal_config', models.JSONField(default=dict, help_text='For signal-based triggers. Defines what signal to watch.')),
                ('task_prompt', models.TextField(help_text='What to do or say when the trigger fires.')),
                ('created_by', models.CharField(help_text='Phone number of the sender who created this task.', max_length=100)),
                ('requires_context', models.BooleanField(default=False, help_text='If True, fetch fresh context at fire time before sending.')),
                ('context_query', models.TextField(blank=True, help_text='CRM or research query to run at fire time if requires_context is True.')),
                ('requires_approval', models.BooleanField(default=False, help_text='If True, send preview to admin before posting.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='config.agentconfig')),
                ('channel_binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='config.channelbinding')),
            ],
            options={
                'verbose_name': 'Scheduled Task',
                'verbose_name_plural': 'Scheduled Tasks',
                'ordering': ['trigger_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('research', 'Company Research'), ('draft', 'Outreach Draft'), ('enrich', 'Prospect Enrichment'), ('summarise', 'Summarise'), ('broadcast', 'Broadcast Content')], max_length=50)),
                ('task_payload', models.JSONField(default=dict, help_text='Input data for the executing agent.')),
                ('result', models.JSONField(blank=True, help_text='Output from the executing agent.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('callback_config', models.JSONField(default=dict, help_text='Where to send the result on completion. e.g. {"type": "whatsapp_group", "channel_id": "..."}')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('executing_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executing_tasks', to='config.agentconfig')),
                ('requesting_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_tasks', to='config.agentconfig')),
            ],
            options={
                'verbose_name': 'Agent Task',
                'verbose_name_plural': 'Agent Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
