# Generated by Django 6.0.6 on 2026-06-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentconfig',
            name='enabled_tools',
            field=models.JSONField(blank=True, default=list, help_text='List of tool names this agent can use.'),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='sender_name_map',
            field=models.JSONField(blank=True, default=dict, help_text='Phone number → display name map. Auto-populated via pushname.'),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='tool_model_map',
            field=models.JSONField(blank=True, default=dict, help_text='Tool name → model name override. e.g. {"crm_query": "gpt-5-nano"}'),
        ),
    ]
