# Generated by Django 6.0.6 on 2026-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_agentconfig_enabled_tools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelbinding',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for the MCP server. e.g. wweb-mcp Bearer token.', max_length=200),
        ),
    ]
